### ISSUE TITLE
Rewards on shards

### ISSUE THREAD

**Issue by vbuterin** [ethereum/consensus-specs#1280]
I see the following rewards existing for validators that are members of persistent committees:

1. Reward for proposing a block
2. Reward for attesting to a block
3. EIP 1559 fee per byte in the block data

Note that in equilibrium, I fully expect (3) to exceed (1) + (2), so in-shard rewards would be net-negative (overcome by transaction fees, which from the perspective of the base protocol are out-of-band).

We have two major possible ways to process these rewards:

1. Add to the (currently nonexistent but it will have to exist for phase 2 anyway) `ShardState` two arrays representing the net penalties or rewards given to the previous and current period committees, respectively. At the end of a period, add the period committee reward list into the crosslink object (alternatively, provide it into the beacon chain through a separate Merkle branch receipt that links into the crosslink data).
2. Process the rewards/penalties probabilistically, eg. based on future randomness making a random 1/N of shard blocks eligible for inclusion into the beacon chain, where rewards and penalties get calculated.

(1) gives precise accounting but is stateful. (2) is stateless but gives imprecise accounting. If we set N = 1024, then there will be on average 256 (~ 9 days / 3 seconds / 1024) blocks per period processed per shard. In the worst case, where full proposal committees are of size 4096 (and assuming per-block committees have size 32), this means that on average a validator will see 2 attester rewards, and 1/16 proposer rewards/penalties. This is a potentially unacceptable level of volatility, as unlucky proposers could end up paying unexpectedly large EIP 1559 fees eg. if they get picked twice and during a fee spike...

**Comment by JustinDrake** [comment]
Am I understanding EIP1559 correctly in the context of shard blocks where transaction fees are out-of-band?

```python
TARGET_GAS_USE = 2**23  # 8,388,608 gas
MAX_GAS_USE = 2**2 * TARGET_GAS_USE
GAS_FEE_DELTA_QUOTIENT = 2**3

# Verify gas use is not too large
assert block.gas_use <= MAX_GAS_USE
# Verify gas fee delta and gas use delta are consistent
parent_gas_fee = shard_state.parent_gas_fee
gas_use_delta = block.gas_use - TARGET_GAS_USE
gas_fee_delta = parent_gas_fee * gas_use_delta // MAX_GAS_USE // GAS_FEE_DELTA_QUOTIENT
if gas_fee_delta == 0 and gas_use_delta != 0:
	gas_fee_delta = gas_use_delta // abs(gas_use_delta)
assert block.gas_fee = parent_gas_fee + gas_fee_delta
# Burn base fees from proposer
proposer_index = get_shard_proposer_index(state, block.shard, block.slot)
assert state.balances[proposer_index] >= block.gas_fee * block.gas_use
decrease_shard_balance(state, proposer_index, block.gas_fee * block.gas_use)
# Set parent gas fee
shard_state.parent_gas_fee = block.gas_fee
```

**Comment by vbuterin** [comment]
Yep! Looks correct to me.

**Comment by mkalinin** [comment]
Could you explain why do we need to burn fees from proposer? Why it's not subtracted from the balance of `tx.origin` as it's specified by EIP-1559?

**Comment by hwwhww** [comment]
closing due to outdated
