### ISSUE TITLE
Networking Spec Review for Light Clients

### ISSUE THREAD

**Issue by jrhea** [ethereum/consensus-specs#1688]
How will a beacon node's conformance to the networking spec impact a light client's and other non beacon node's ability to join the network? 
 Specific questions/concerns:
- beacon_block topic:
  - how can a non beacon node join this topic AND not risk being disconnected if it can't currently perform the block validation?  Options:
      - don't fwd blocks 🤷
      - zk proofs?
      - allow non beacon nodes to fwd without validating
- req/resp:
    - should beacon nodes drop nodes that do not implement all req/resp messages?  If so, this will impact a non beacon node's ability to participate. 

In general all MUSTs should be reviewed through the lense of non beacon nodes.  If it is decided that the phase 0 network will not be non beacon node friendly, then we should consider how that will impact network tooling efforts.

**Comment by hwwhww** [comment]
closing due to outdated
