### ISSUE TITLE
Slashing  penalty needs to depend on multiplicity of offending messages

### ISSUE THREAD

**Issue by kladkogex** [ethereum/consensus-specs#1860]
Currently the slashing penalty does not depend on how many concurrent offending messages were signed by the malicious validator.

As an example, if a malicious proposer signs 1000 alternative proposals, effectively mounting a massive DOS attack  on the network she will still incur the minimum penalty  of 1 ETH, assuming no other validators misbehave.

Note that once the validator is slashed, she becomes unslashable and, therefore, immune to further whisteblower messages.  

What I propose, is that if multiple offending messages for the same protocol phase are submitted by whistleblowers,  the validator is punished for each new message submitted.  As an example if the validator created 1000 offending blocks, the first 32 whistleblower submissions will be paid and the validator will essentially be fully slashed.

**Comment by djrtwo** [comment]
You are certainly correct that once a validator goes rogue, they can make an infinite number of valid-looking message for "free".

To mitigate this DoS issue, there are validation conditions on the wire that prevent broadcasting of multiple valid blocks/attestations for the same validator(s) in the same time range (slot for block, epoch for attestation)

Check all the gossip conditions out here: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#global-topics

Relevant conditions:
* [IGNORE] The block is the first block with valid signature received for the proposer for the slot, signed_beacon_block.message.slot.
* [IGNORE] The aggregate is the first valid aggregate received for the aggregator with index aggregate_and_proof.aggregator_index for the epoch aggregate.data.target.epoch.
* [IGNORE] There has been no other valid attestation seen on an attestation subnet that has an identical attestation.data.target.epoch and participating validator index

(there are similar conditions for the other operation types/topics)
