### ISSUE TITLE
Deposit contract should reject invalid signatures

### ISSUE THREAD

**Issue by q9f** [ethereum/consensus-specs#2081]
Deposits are effectively lost if they are formatted properly but contain an invalid signature. 

* Example: https://ethereum.stackexchange.com/questions/87116/why-did-an-event-fire-even-though-etherscan-suggests-it-failed
* Example: https://goerli.etherscan.io/tx/0x342d3551439a13555c62f95d27b2fbabc816e4c23a6e58c28e69af6fae6d0159
* Example: #2071

The deposit contract can not determine between valid and invalid signatures if the deposit "looks good" otherwise. For testnets we never really bothered but for mainnet that would effectively burn the funds.

We should track implementation of [EIP-2357](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2537.md) on Ethereum 1.x and adapt the deposit contract accordingly once BLS precompiles are available for signature verification.

**Comment by ralexstokes** [comment]
for reference, i started a "deposit verifier" contract using the EIP-2537 precompiles: https://github.com/ralexstokes/deposit-verifier/blob/master/deposit_verifier.sol

i have heard a range of opinions on how much of a problem people actually view this being -- for example, we could argue signature checks should happen before the data goes on-chain. i agree that having (at the least) the option to verify a deposit before funds are moved would be very beneficial to validators

**Comment by q9f** [comment]
While acknowledging the low probability that we see this implemented for phase 0 launch, I would always encourage a conservative approach to security: if it's possible to submit invalid signatures, users will find a way to do so.

A data point from the testnets: every deposit contract we used thus far had seen invalid deposits. For mainnet, we need to tripple check all clients and tooling.

**Comment by ralexstokes** [comment]
yep, fully agreed :) 

we _are_ triple-checking everything and bad deposits still get through...

unfortunately this entire line of work is blocked on deploying the precompiles on eth1 which i don't think will happen in time for eth2 mainnet like you point out... we can definitely have this at the ready when the precompiles go online!

**Comment by dapplion** [comment]
@q9f is ok with letting this one go :)
