### ISSUE TITLE
Can pubkey and withdrawal_credentials be generated with different mnemonics?

### ISSUE THREAD

**Issue by seancheen** [ethereum/consensus-specs#2128]
I want to deposit for multiple validators, but I want to use a private key generated by another mnemonic for the withdrawal certificate,Can pubkey and withdrawal_credentials be generated with different mnemonics?

**Comment by protolambda** [comment]
Yes, that should be possible, although it is recommended to use standard tooling to avoid unexpected problems. @CarlBeek might be able to help with deposit CLI specific questions.
