### ISSUE TITLE
Merge discussion and todos from #2257

### ISSUE THREAD

**Issue by djrtwo** [ethereum/consensus-specs#2280]
#2257 got the basic merge spec to a solid footing. The following are the list of discussion points and todos that were *not* completed within the context of that PR. These are left for future work and discussion.

*Note*: This is not an exhaustive merge todo list but is instead only open points from #2257

- [x] [Debates](https://github.com/ethereum/eth2.0-specs/pull/2257#discussion_r599021130) around `application_state_transition` (should the spec know about the `ApplicationState` or just about its root hash) 
- [ ] [Consider eliminating](https://github.com/ethereum/eth2.0-specs/pull/2257/files#r598997175) `uint256` requirement on beacon-chain side in `PoWBlock` and TD comparison 
- [ ] Consider max block size in relation to `ApplicationPayload` and where should such validation happen. At gossip, inside beacon chain, or just in application gas limit. Max TX size times max txs is 16GB!
- [X] [Consider `Union` type](https://github.com/ethereum/eth2.0-specs/pull/2257#issuecomment-807505782) for transaction list with a single `OPAQUE_SELECTOR` for first merge fork. More specific, structured selectors for each TX type to follow
- [x] [Post-London](https://github.com/ethereum/eth2.0-specs/pull/2257#discussion_r599048199) add `base_fee` to `ApplicationPayload` 
- [x] Add `Hash32` type to provide more specificity than `Bytes32` and to further disambiguate from `Root`
- [ ] Modularize components of fork choice in phase 0 to better facilitate code reuse https://github.com/ethereum/eth2.0-specs/pull/2257#discussion_r599015500
- [ ] [Potentially rename]( https://github.com/ethereum/eth2.0-specs/pull/2257#discussion_r599049800) `Eth1Data` -- `DepostContractData`
- [x] [Consider adding fields to block](https://github.com/ethereum/eth2.0-specs/issues/2280#issuecomment-808493936) to ensure there is a clean one-way map from `ApplicationPayload` to RLP block

**Comment by vbuterin** [comment]
I would also say consider adding some fields back in despite the redundancy. Particularly, adding the block prevhash back in to the `ApplicationPayload` seems like it could easily do more good than harm.

**Comment by mkalinin** [comment]
PR addressing additional fields in `ApplicationPayload`, https://github.com/ethereum/eth2.0-specs/pull/2295

**Comment by vshvsh** [comment]
Can we pipe becon chain block roots to eth1x as well? Would be very useful for applications that depend on beacon chain, like staking pools, which are forced to use oracle these days.

**Comment by mcdee** [comment]
> Can we pipe becon chain block roots to eth1x as well? Would be very useful for applications that depend on beacon chain, like staking pools, which are forced to use oracle these days.

The beacon _state_ root would be a useful addition, not sure that individual block roots would gain anything.

**Comment by mkalinin** [comment]
There is a plan to introduce `BEACONBLOCKROOT` opcode after the Merge. Exposing block roots allows for reading data from either a block or a state.

**Comment by mkalinin** [comment]
(4) Addressed in https://github.com/ethereum/eth2.0-specs/pull/2472
