### ISSUE TITLE
suggestion: use custom exceptions rather than `Exception`

### ISSUE THREAD

**Issue by sammiee5311** [ethereum/consensus-specs#2614]
Hi, I just found out that there are some `Exception` on codes.
Maybe, it's more clarity to use custom exceptions rather than `Exception` ?

- example
`raise Exception('invalid target name: "%s"' % name)` -> `raise InvalidTargetName()`
`raise Exception('Config file "%s" does not exist' % config_path)` -> `raise FileNotExist()`

[code1](https://github.com/ethereum/consensus-specs/blob/c396ee1e3f6bea1cfbe0159302c9391b0811c37c/setup.py#L870)
[code2](https://github.com/ethereum/consensus-specs/blob/c396ee1e3f6bea1cfbe0159302c9391b0811c37c/setup.py#L876)

**Comment by hwwhww** [comment]
@sammiee5311 👋

- `setup.py` is the entry of the pyspec build and it's already too long. Personally, I'd like it to be simpler.
- It could be fine to use some built-in Exceptions. e.g., for your given examples, we can just use [KeyError](https://docs.python.org/3/library/exceptions.html#KeyError) and [FileNotFoundError](https://docs.python.org/3/library/exceptions.html#FileNotFoundError).
- For testing tools or specs, we now only use custom exceptions for the cases that we want to catch.
    - [`SkippedTest`](https://github.com/ethereum/consensus-specs/blob/cb7c81eb96e9d748abe7248a132423b6326d605a/tests/core/pyspec/eth2spec/gen_helpers/gen_base/gen_runner.py#L174) will be caught in the test runner.
    - #2366 will use `ValidationError` for spec validations. `ValidationError` exceptions will be caught in pyspec tests.


IMO, for `setup.py`, we can just use the basic `Exception` or Python built-in exceptions.

**Comment by sammiee5311** [comment]
Thanks for the detailed explanation, @hwwhww !

Right, I've just checked one the the issues that `setup.py` contains lots of hardcoded information.

I will close this issue, thanks again!
