### ISSUE TITLE
Add getter to ExecutionEngine to get TTD

### ISSUE THREAD

**Issue by dapplion** [ethereum/consensus-specs#2643]
If the execution and consensus layer have different total terminal difficulty (TTD) it results in bad failures:

- If consensus TTD1 > execution TTD2: Execution client will stop producing blocks at TTD2 and consensus will be expecting a transition block with TTD1 that will never come, stalling execution forever.
- If consensus TTD1 < execution TTD2
  - if execution allows prepare_payload calls: consensus and execution will fork maintaining two correct chains both with execution data. However, once TTD2 is reached execution will re-org to the consensus chain. The resulting canonical chain won't contain a long range of blocks without execution data but it will drop state that explorers and users consider canonical. 
  - if execution NOT allows prepare_payload calls: consensus will try to create blocks but since prepare_payload fails each attempted block can only reference the merge block at TTD1. Once TTD2 happens execution will re-org to a head that points to the merge block dropping its chain for a long gap in history.

To reduce the chance of this failure cases, the consensus client could check that its TTD matches the execution client TTD. If TTDs don't match, panic or very visibly alert the user. To allow updating nodes in any order absence of this method should not result in a error. Also a different TTD could only result in panic if TTD has been manually overwritten.

CC @mkalinin

**Comment by MicahZoltu** [comment]
Is TTD not already part of the synchronization API?  cc @mkalinin

**Comment by mkalinin** [comment]
What if we hardcode TTD on the EL (execution layer) side and have a `--terminal-total-difficulty-override` setting there as well? Then CL can poll this parameter via `engine_getTransitionState` method, polling matter because of EL can be restarted with an override and CL should always be on spot.

This approach should reduce the number of potential failure points, in particular in how to sync this value between the layers if it is defined in each of them with an option to be overridden.

**Comment by ajsutton** [comment]
> +1 on _only_ putting this in the EL and requiring CL to get it. Definitely reduces failures in synchronization between the two layers

The downside however is that now the CL can't startup until the EL is already running and accepting requests. Previously it would have been able to startup, begin finding peers and begin optimistic sync.

Given the huge number of things that already have to be in-sync between the CL and EL, I'm not sure the complexity of having to retrieve this and continuously poll for changes is going to reduce bugs.  It will definitely increase complexity significantly and that usually leads to an increase in bugs.

**Comment by mkalinin** [comment]
Addressed in https://github.com/ethereum/EIPs/pull/4397
