### ISSUE TITLE
Build block with empty transactions if prepare_payload fails

### ISSUE THREAD

**Issue by dapplion** [ethereum/consensus-specs#2644]
If the execution client is not able to prepare or deliver a block the consensus client could create a valid execution payload on its own with no transactions. Before skipping the slot, this would allow consensus operations to be included on-chain, a lesser of two evils

**Comment by dapplion** [comment]
> > Yes, the parent has been validated by execution layer, but execution engine is not available to produce the next block. Other consensus clients could validate this block without execution layer provided it has 0 transactions.
> 
> Producing empty payload is the potential fallback behaviour for CL client in this case. This case is not that frequent, though. The question is would CL want to support RLP and keccak256 to handle it, should be up to implementation

It could help in a network wide outage where Geth experiments a critical failure, it won't stall consensus too, only EL.

**Comment by dapplion** [comment]
> Right and it should be possible to be implemented on CL side without an update to the spec

While it does not affect the spec it can significantly alter network behavior. Would a note or recommendation by appropriate?

**Comment by mkalinin** [comment]
The first note that has been discussed in this issue has been added to the spec https://github.com/ethereum/consensus-specs/pull/2703. I am closing the issue as everyone seems to be agree on leaving the opportunity of building empty payload as a fallback out of specification.
