### ISSUE TITLE
CL reaction to SYNCING response status post-Merge

### ISSUE THREAD

**Issue by mkalinin** [ethereum/consensus-specs#2735]
This RFC is originated by discussion in https://github.com/ethereum/consensus-specs/issues/2732

Assuming the network post-Merge, suppose a node has caught up with the head and stays online. Then suddenly a subsequent call to `executePayload` is responded with `SYNCING` status meaning that EL is missing data required to verify the payload. If this happens with a side chain then CL obviously may keep importing, attesting and proposing on the canonical one.

The things become tricky when this happens on the canonical chain, CL has the following options:
1. Import optimistically, stop attesting and proposing until the sync is finished
2. Import optimistically, attest to and propose on top of fully verified head

**Comment by djrtwo** [comment]
When not at the Merge transition boundary, I would argue that (1) is generally okay, as it looks like some sort of EL sync failure.

It's probably still valuable (and okay) to attest (as in suggin such a case at least for some depth of SYNCING (e.g. within 32 slots). Essentially, if my EL goes out of sync for a few slots, I can still say what I see as the head (a few slots back) at slot N and help with finality. Once the depth exceeds ~32 slots, shufflings would no longer map to mainnet and there is little to no value to attesting.

**Comment by mkalinin** [comment]
I am thinking about one crazy edge case scenario. User hot swapping EL software with the new client version that has a bug fix and partially invalidates the chain that has been canonical to the previous view of CL. In this case `SYNCING` will end up with `INVALID` + `latestValidHash` set to a block that is several blocks behind the head. Attesting to the head in this case might result in attesting to invalid block.

**Comment by djrtwo** [comment]
Ah, I see that... good point

**Comment by mkalinin** [comment]
Addressed in https://github.com/ethereum/consensus-specs/pull/2770:
> Let only a node which returns `is_optimistic(head) == True` be an *optimistic node*. Let only a validator on an optimistic node be an *optimistic validator*.
> An optimistic validator MUST NOT produce a block
> An optimistic validator MUST NOT participate in attestation

In other words, if the payload of the head of the chain turned EL into `SYNCING` a validator must stop attesting and proposing until the sync is finished.
