### ISSUE TITLE
CI updates: add Python 3.10 and drop Python 3.8 support

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#2780]
### Issue

For efficiency and using more new built-in libraries, we can consider dropping Python 3.8 support now.

**Comment by hwwhww** [comment]
Note that it may affect the `eth2spec` Python package users if we drop Python 3.8 support in the package setting and start to write Python 3.9-new code.

**Comment by ChihChengLiang** [comment]
I'm also preparing an update on future python versions https://github.com/ChihChengLiang/milagro_bls_binding/issues/34

**Comment by djrtwo** [comment]
When we move from 3.8 to 3.10, we should build test vectors with both and ensure they have the same output

**Comment by ChihChengLiang** [comment]
@hwwhww @protolambda I have the milagro_bls_binding [1.8.0](https://pypi.org/project/milagro-bls-binding/1.8.0/) ready. It works with my macos/M1/python3.10 setting.
