### ISSUE TITLE
Missing bellatrix random test-gen

### ISSUE THREAD

**Issue by protolambda** [ethereum/consensus-specs#2813]
The `random` blocks test-generator is not running for bellatrix:
https://github.com/ethereum/consensus-specs/blob/2232d767352c72653467ecef62d88647fd4cd2ef/tests/generators/random/main.py#L9

Verified they are missing in spec tests of `v1.1.8`

Shall I make a PR to enable this test-generator for bellatrix, or was it not enabled intentionally?

**Comment by djrtwo** [comment]
I believe this was unintentional. enabling for the release coming in next few days would be excellent 👍

**Comment by protolambda** [comment]
So unlike other test types, the test-cases are specific to a single phase, and generated with code. Can't just update the main.py to enable the tests for bellatrix.

Looks like we need to update the code-generator with Bellatrix support, somewhere here: https://github.com/ethereum/consensus-specs/blob/a890d04a62e44a59bddda4a2bc2d4bbae8f7e568/tests/generators/random/generate.py#L243

@ralexstokes can you help here?

**Comment by ralexstokes** [comment]
it is pretty straightforward to test the "default" case but the test logic will need to be extended to start testing "interesting" merge scenarios which this suite of tests would be well-positioned to address... i'd want to circle around with a few other efforts to understand the latest on merge testing before i dive into building these out

i'll open a PR with the "default" tests enabled and can extend in a future PR
