### ISSUE TITLE
Rename repository name to "Consensus Layer Specification"

### ISSUE THREAD

**Issue by uink45** [ethereum/consensus-specs#2819]
This issue proposes a name change for the repository to "Consensus Layer Specification". The same is proposed for the "execution-specs" repository for maintaining consistency (link: https://github.com/ethereum/execution-specs/issues/440).

**Comment by ralexstokes** [comment]
thanks for raising this issue and i'd have to lean towards keeping things as they are. 

we just had a "great renaming" and  it introduced a lot of churn throughout the ethereum software ecosystem (that is still being resolved) so it's likely not a great time to go changing the name of this repo further

**Comment by mratsim** [comment]
Additionally, "Consensus Layer Specification" is too long and adds nothing to https://github.com/ethereum/consensus-specs
