### ISSUE TITLE
Beacon chain spec: compute_domain is using big Endian format

### ISSUE THREAD

**Issue by jonathanpwang** [ethereum/consensus-specs#2874]
In https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#compute_domain the last line of appending domain_type to fork_data_root is assuming the byte vectors are in big Endian format. Meanwhile the spec is using little Endianness.

**Comment by hwwhww** [comment]
hi @jonathanpwang 
Could you explain more about "assuming the byte vectors are in big Endian format"?
I think it just appending and [domain types](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#domain-types) are sort of in little-endian format.

**Comment by jonathanpwang** [comment]
hi @hwwhww 
I mean that in `compute_domain` if `fork_data_root` is `0x123456` (shortening length for simplicity) and `domain_type` is `0x0000` then the `domain` will be `0x000012` by appending `domain_type` to the front in hex. I believe this is what actually happens on-chain?
 
However in little-endian format `fork_data_root` is `[0x56, 0x34, 0x12]` and `domain_type` is `[0, 0]` so the command `domain_type + fork_data_root[:-2]` will give `[0, 0, 0x56]` in little-endian format, which translates to `0x560000` in hex.

**Comment by ralexstokes** [comment]
"endianness" is a property determined by context, not a transformation you can apply like you are suggesting with `fork_data_root` as `563412`

in the context of generating a signature domain, the "endianness" doesn't really matter and like @hwwhww is saying we just concatenate the bytes here

if you look in the spec where we use `ENDIANNESS` you can see where it is relevant: mapping from integers to bytes and back


going to close this issue as it doesn't have a relevant change; feel free to re-open if you have another point to make :)

**Comment by jonathanpwang** [comment]
@ralexstokes I understand `ENDIANNESS` is for mapping integers to bytes and back. 

I am saying that right now the spec is saying to append `domain_type` bytes to the front of the byte array. If `domain_type` is `0x0000` then when you convert the bytes to an integer in little endian this has the effect of multiplying by `2 ** 16`. 

However I think the effect you want is to "do nothing". This means you should be appending `domain_type` bytes to the **end** of the byte array.
