### ISSUE TITLE
Need to update `get_validator_from_deposit` for `capella` fork

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/consensus-specs#2909]
refer to `get_validator_from_deposit` here: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#deposits

we have changed the `Validator` record in `capella` so need to update this in the spec

**Comment by hwwhww** [comment]
Closing since the latest Capella doesn't change `Validator` 🎉
