### ISSUE TITLE
Name discrepancy between spec and presets for WITHDRAWAL_QUEUE_LIMIT

### ISSUE THREAD

**Issue by marioevz** [ethereum/consensus-specs#2920]
Capella spec (https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md) lists preset field `WITHDRAWAL_QUEUE_LIMIT`, while the preset YAML files (https://github.com/ethereum/consensus-specs/blob/dev/presets/mainnet/capella.yaml#L12) list the field as `WITHDRAWALS_QUEUE_LIMIT` (with an `S`).

Other examples for a discrepancy between the spec and the preset files are:
`MAX_SAMPLES_PER_BLOCK` in https://github.com/ethereum/consensus-specs/blob/dev/presets/mainnet/sharding.yaml, vs `MAX_SAMPLES_PER_BLOB` in https://github.com/ethereum/consensus-specs/blob/dev/specs/sharding/beacon-chain.md
`TARGET_SAMPLES_PER_BLOCK` in https://github.com/ethereum/consensus-specs/blob/dev/presets/mainnet/sharding.yaml, vs  `TARGET_SAMPLES_PER_BLOB` in https://github.com/ethereum/consensus-specs/blob/dev/specs/sharding/beacon-chain.md

**Comment by ralexstokes** [comment]
thanks for this!

I don't think we are actively maintaining the `sharding` specs at the moment and they are more illustrative as we iterate towards something like EIP-4844 + danksharding.

the config issue w/ the `capella` fork was left over from a previous refactor -- do you mind making a PR?

**Comment by ralexstokes** [comment]
https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#state-list-lengths

thank you!

**Comment by ralexstokes** [comment]
Fixed in #2921. thank you @marioevz !
