### ISSUE TITLE
Need help for beacon simulation

### ISSUE THREAD

**Issue by zsharifian** [ethereum/consensus-specs#2936]
Hello to all 

For my thesis work, I need to run Beacon on a some lab network nodes (as clients) in my university (by defining the desired delay on each node), and of course apply some changes on it. I also need to have network view.

Can anyone guide me on choosing the appropriate code to install on client' nodes and how to have a network view on the activity of these clients?

Regard

**Comment by dapplion** [comment]
Hey @zsharifian I would encourage you to join the Ethereum R&D discord for this types of questions, please follow this link https://discord.com/invite/qGpsxSA or see Danny's twit if you need legitimacy https://twitter.com/dannyryan/status/1506635912163307527?s=20&t=Utye4iS9xPOQy7Bd6d3XWg

I'm sure you'll get a lot of help there :+1:

**Comment by zsharifian** [comment]
> Hey @zsharifian I would encourage you to join the Ethereum R&D discord for this types of questions, please follow this link https://discord.com/invite/qGpsxSA or see Danny's twit if you need legitimacy https://twitter.com/dannyryan/status/1506635912163307527
> 
> I'm sure you'll get a lot of help there 👍

Thanks so much
