### ISSUE TITLE
[Question] Finaliser can change his opinion after vote casted?

### ISSUE THREAD

**Issue by Nk185** [ethereum/consensus-specs#2963]
Hi guys, 

As per [Casper FFG](https://arxiv.org/pdf/1710.09437.pdf), a validator must not vote within the span of its other votes, that is:

> h(s1) < h(s2) < h(t2) < h(t1)

which is [represented](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#is_slashable_attestation_data) in the spec as:

> (data_1.source.epoch < data_2.source.epoch and data_2.target.epoch < data_1.target.epoch)

Now, what happens if validator cast `v1 = {sourceH: 0, targetH: 5}` and later `v2 = {sourceH: 0, targetH: 6}`? The above function will yield `false` for the `0 < 0` check, yet such votes may be included in the blockchain...
Does it mean that validator node is allowed to change its mind (e.g. if, after a split-brain, he realises that he voted for the wrong fork) w.r.t. which fork he finalises? If so, is there a document that discusses how votes are tallied in this case, and, particularly, what happens if targets' roots belong to different forks?

I understand that normally it shouldn't be a problem because you finalise epoch `n` in epoch `n+1` so you simply can't reference this ongoing `n+1` as a target, but once there are more than one non-finalised epochs this becomes relevant:
assuming sequence `G <- B1 <- B2 <- B3 <- C1 <- B5 <- B6 <- B7 <- C2 <- B9` where `G` is genesis, if checkpoint `C0` for some reason is not justified in within `B5...B7`, yet a validator casted `v1 = {sourceH: 0, targetH: 1}`, that included within that range, then the validator can cast `v2 = {sourceH: 0, targetH: 2}` starting from `B9`...

**Comment by ralexstokes** [comment]
this is fine -- v1 and v2 do not form surround votes

and the definition supports liveness of the protocol -- e.g. a validator votes for some target and later changes to a different target as the rest of the validator set moved to this later target for whatever reason

the way the slashing conditions work, after a vote by a validator has been finalized, it cannot change unless that validator did something provably slashble
