### ISSUE TITLE
EIP4844: Impove performance by avoiding merkle trees when generating KZG challenges

### ISSUE THREAD

**Issue by asn-d6** [ethereum/consensus-specs#2980]
Both in [compute_aggregated_poly_and_commitment](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/validator.md#compute_aggregated_poly_and_commitment) and in [validate_blobs_sidecar](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/validator.md#validate_blobs_sidecar) we are generating challenge scalars using [hash_to_bls_field()](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/validator.md#hash_to_bls_field) which calls `hash_tree_root()`.

There is actually no reason to compute merkle roots when we are generating these challenge scalars. We should instead just straight sha256 hash the values we care about.

Doing this change will improve performance when we are computing and verifying KZG proofs.

(/cc @hwwhww @Inphi @protolambda )

**Comment by asn-d6** [comment]
@hwwhww Thanks for the patch! I think @Inphi is gonna implement the change on his side pretty soon, so let's wait for his performance results before we merge this.

**Comment by Inphi** [comment]
This indeed yields a significant performance improvement:
```
name                 old time/op    new time/op    delta
VerifyMultiple/8-6     73.9ms ± 0%    40.7ms ± 0%   ~     (p=1.000 n=1+1)
VerifyMultiple/16-6     138ms ± 0%      81ms ± 0%   ~     (p=1.000 n=1+1)

name                 old alloc/op   new alloc/op   delta
VerifyMultiple/8-6     25.2MB ± 0%    22.1MB ± 0%   ~     (p=1.000 n=1+1)
VerifyMultiple/16-6    50.4MB ± 0%    44.1MB ± 0%   ~     (p=1.000 n=1+1)

name                 old allocs/op  new allocs/op  delta
VerifyMultiple/8-6       400k ± 0%      301k ± 0%   ~     (p=1.000 n=1+1)
VerifyMultiple/16-6      800k ± 0%      603k ± 0%   ~     (p=1.000 n=1+1)
```

Verifying blob txs is about 40-50% faster with this.

**Comment by asn-d6** [comment]
Closing this since https://github.com/ethereum/consensus-specs/pull/2981 has been merged. Thanks all!
