### ISSUE TITLE
Should we require that validators do not submit blocks after the slot has finished?

### ISSUE THREAD

**Issue by potuz** [ethereum/consensus-specs#2984]
The [honest validator guide states](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#block-proposal)
> A validator is expected to propose a [SignedBeaconBlock](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#signedbeaconblock) at the beginning of any slot during which is_proposer(state, validator_index) returns True.

I want to hear opinions on whether we should require clients to not submit a proposal if in their view of their wall clock, their slot has already passed.

**Comment by dapplion** [comment]
If there's a DOS attack on execution that could break liveness? i.e. in extreme degenerate cases do we prefer late blocks or no blocks?

**Comment by mcdee** [comment]
Seems a bit of a pointless requirement in a world where clock skew is a thing.  Beacon nodes cannot rely on blocks not arriving late, and validator clients are already incentivized to produce a block as quickly as possible.

**Comment by mkalinin** [comment]
Clients will have to be capable of handling late blocks regardless, thus seems there is no value in restricting honest behaviour this way, it may even become detrimental to the health of the network in some edge cases (couple of them were mentioned above).

**Comment by potuz** [comment]
Closing this as the overwhelming majority thinks it's a bad idea, and I myself got convinced by a couple of points.
