### ISSUE TITLE
`consensus-spec-tests`'s `diagnostics.json` file path

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#2988]
###  Issue
Currently, after running test generator, we will get the summary files:
```
consensus-spec-tests/tests/diagnostics.json
consensus-spec-tests/tests/diagnostics.json.lock
```

These files are good for analyzing the test cases. (Thank @ralexstokes!) 

But we may not want to upload these files to `consensus-spec-tests` and the tarballs. Especially when the test vectors are not generated with only one command.

### Solution ideas
1. Generate these files to `consensus-spec-tests/` folder rather than `consensus-spec-tests/tests/` folder
    - Pros: we can have clear files
    - Cons: `"--output-dir` is `consensus-spec-tests/tests/`, it feels wrong to jump out of the given scope.
2. Ignore these files in the `consensus-spec-tests` repo and allow including these files in tarballs.
    - Pros: easy
    - Cons: no...? just client teams have to ignore it.
3. No change. Just include the diagnostics to the `consensus-spec-tests` repo and tarballs.
    - Pros: easy
    - Cons:
        - it creates extra git diff
        - `diagnostics.json` may be confusing when we generate the test vectors in separate runs. However, it may not be a problem anymore once we have the generator CI/CD soon.

I usually manually delete these files when I want to generate the tarball of a specific runner. But sometimes I forget. 😅 I'm inclined to solution 2.

/cc @ralexstokes  @djrtwo

**Comment by ralexstokes** [comment]
yeah, is there a concrete problem with including them in the test artifacts? otherwise (2) sounds good

**Comment by hwwhww** [comment]
Done. Added file paths to .gitignore in https://github.com/ethereum/consensus-spec-tests

I realized that since we normally compress artifacts (`mainnet`, `minimal`, and `general`) separately, the `diagnostics.json` files should not be included in the tarballs. 😆
