### ISSUE TITLE
Capella: Validator index in Withdrawal?

### ISSUE THREAD

**Issue by mcdee** [ethereum/consensus-specs#3020]
Looking at the `Withdrawal` type, is there value to having the validator index in here?  At current there doesn't seem to be a way of tying a withdrawal to a particular validator (even if the beacon state root were available in the EVM) so this would provide that linkage.

**Comment by djrtwo** [comment]
I'm not opposed. It comes at a cost to block size but other than that seems safe/fine.

The current idea is that the `withdrawal_index` can be tracked when created for the validator but that's not very offline-proof

**Comment by hwwhww** [comment]
close via #3050
