### ISSUE TITLE
Rebase 4844 on Capella

### ISSUE THREAD

**Issue by djrtwo** [ethereum/consensus-specs#3044]
We should stabilize Capella with any of the proposed changes and then rebase 4844 specs on top of it.

Some clients (e.g. lighthouse) have these features developed in the same branch and can only turn on features sequentially, thus 4844 cannot be enabled without Capella. To ensure we can adequately test 4844 *soon*, we need to get it into a place where all clients can follow the same consenses rules  with the rebase (which currently from what I understand is not the case).

We can wait another couple of weeks for governance discussions as there could be a chance that 4844 is shipped prior to/without capella, but based on conversations at devcon, this seems to be on the extremely low probability side of things

**Comment by Where-2** [comment]
Whilst implementing any such coding unfortunately there is binary.  Opposition to governance   Positive equals negative.  How do you secure a system that is always preyed upon

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Danny Ryan ***@***.***>
Sent: Monday, October 17, 2022 8:49:51 AM
To: ethereum/consensus-specs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ethereum/consensus-specs] Rebase 4844 on Capella (Issue #3044)


We should stabilize Capella with any of the proposed changes and then rebase 4844 specs on top of it.

Some clients (e.g. lighthouse) have these features developed in the same branch and can only turn on features sequentially, thus 4844 cannot be enabled without Capella. To ensure we can adequately test 4844 soon, we need to get it into a place where all clients can follow the same consenses rules with the rebase (which currently from what I understand is not the case).

We can wait another couple of weeks for governance discussions as there could be a chance that 4844 is shipped prior to/without capella, but based on conversations at devcon, this seems to be on the extremely low probability side of things

**Comment by hwwhww** [comment]
closing via #3052
