### ISSUE TITLE
Standardize test case naming

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3118]
### Issue

We currently have test case names with `test_invalid_...`,`test_fail_...`, `test_..._invalid`, `test_valid_...`, `test_..._valid`... .etc. It would be nice if they were in the same format.

### Proposal
- Using prefix `test_invalid_<DESCRIPTION>` for the test case that is expected to fail, i.e., post-state does not exist.
- Using simple `test_<DESCRIPTION>` for the test case that is expected to succeed, i.e., post-state exists.

**Comment by djrtwo** [comment]
I like it!

**Comment by hwwhww** [comment]
closing via https://github.com/ethereum/consensus-specs/pull/3143
