### ISSUE TITLE
Use of integer division in fork choice on_block handler

### ISSUE THREAD

**Issue by benjaminion** [ethereum/consensus-specs#3238]
The fork choice `on_block()` handler contains the following line:

    is_before_attesting_interval = time_into_slot < SECONDS_PER_SLOT // INTERVALS_PER_SLOT

This line performs integer division. In Ethereum's mainnet case `SECONDS_PER_SLOT` is `uint64(12)`, and `INTERVALS_PER_SLOT` is `uint64(3)`, so it happens to behave as we expect.

However, for other chains such as Gnosis Beacon chain (where `SECONDS_PER_SLOT` is 5) integer division might lead to unexpected behaviour. It would be more correct to use floating point division here (as the Honest Validator spec does).

Question: is floating point division defined for between two `uint64` types?

**Comment by ralexstokes** [comment]
the intent is that numeric types in this specification are unsigned integers and any suggestion of division is for _integer division_

there is no floating point embedding into SSZ (and this is for good reason around the non-determinism of common floating point systems)

use of the python operator `/` should be interpreted as dividing two integer values and yielding a third integer value

**Comment by benjaminion** [comment]
On reflection, since `store.time` is also an integer, per the spec, `time_into_slot` will be an integral number of seconds. So using floating division here would not make any difference to the less-than comparison.

I guess that chains using a `SECONDS_PER_SLOT` that is not a multiple of `INTERVALS_PER_SLOT` (such as Gnosis) will just have to be off-spec on this.

Closing.

**Comment by dankrad** [comment]
Not that I would want to change this now, but retrospectively, measuring time in seconds is probably not very granular, and it would have been better to use milliseconds or something like that. We might need to do this as a later time when we need more granular slot subdivisions (such as when we introduce in-protocol PBS)

**Comment by dapplion** [comment]
For the record Lodestar uses floats here in the context of fork-choice only. Nothing broke either
