### ISSUE TITLE
Question: what is the difference between `LightClientUpdate`, `LightClientFinalityUpdate` and `LightClientOptimisticUpdate `

### ISSUE THREAD

**Issue by jimzk** [ethereum/consensus-specs#3252]
I am studying the light client specs and have some confusion. I don't know where can I get explained and can only post my confusion here (sorry if here is not the appropriate place).

From the [altair/light-client/sync-protocol.md](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md#lightclientupdate) it seems that `LightClientOptimisticUpdate` and `LightClientFinalityUpdate` will be converted to `LightClientUpdate` and be processed in the same method. Why do we distinguish them? Especially for  `LightClientUpdate` and `LightClientFinalityUpdate`, the difference is that the latter does not have `next_sync_committee` and `next_sync_committee_branch`. Why can't we get the `next_sync_committee`, as it has been finalized? If so, then these type is the same.

Also, the doc [`altair/light-client/light-client.md`](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/light-client.md) says

> When `finalized_period + 1 >= current_period`, the light client keeps observing [`LightClientFinalityUpdate`](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md#lightclientfinalityupdate) and [`LightClientOptimisticUpdate`](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md#lightclientoptimisticupdate). Received objects are passed to [`process_light_client_finality_update`](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md#process_light_client_finality_update) and [`process_light_client_optimistic_update`](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/light-client/sync-protocol.md#process_light_client_optimistic_update). This ensures that `finalized_header` and `optimistic_header` reflect the latest blocks.

The `current_period` is computed from the clock and genesis block time. If these two values are correct then `current_period` is correct as well, and it will always represent the latest committee period.  So I think this case only includes `finalized_period == current_period - 1` and `finalized_period == current_period`. But why here it uses `LightClientFinalityUpdate` instead of `LightClientUpdate` to update `finalized_header` in storage?

Very much appreciate it if someone could give some insight or provide valuable readings for better understanding.

**Comment by dapplion** [comment]
LightClientFinalityUpdate, LightClientOptimisticUpdate are meant to serve different lightclient consumers. If you want to follow the tip of the chain, LightClientOptimisticUpdate gives you the min data required to do so without any bloat. LightClientFinalityUpdate contains more data to prove that a header was finalized.
