### ISSUE TITLE
Deneb crypto helpers test coverage

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3258]
Currently, we don't have tests to cover these functions:

- `polynomial-commitments.md`
  - [x] `verify_kzg_proof` wrapper
  - [x] `compute_kzg_proof` wrapper
  - [x] `verify_blob_kzg_proof`
  - [x] `validate_kzg_g1`: `if b == G1_POINT_AT_INFINITY` case
- `validator.md`
  - [x] `get_blob_sidecar_signature`
  - [x] `validate_blobs_and_kzg_commitments`

Except for `validate_kzg_g1`, they are not used in the core protocol. Still, it's better to add unit tests for them.

**Comment by dankrad** [comment]
Done in #3283
