### ISSUE TITLE
Function `process_withdrawals` in `beacon-chain.md` may skip withdrawable validators for one sweep

### ISSUE THREAD

**Issue by andreas-blockswap** [ethereum/consensus-specs#3310]
While reading the [beacon-chain.md spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md), I have come across something which seems slightly off. Not a serious issue, but the solution seems simple, so let me explain. 

### Problem

The new [`process_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-process_withdrawals) function calls [`get_expected_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-get_expected_withdrawals) to get a list of expected withdrawals. Suppose that the input state is satisfying:

- `state.next_withdrawal_validator_index == 0`
- `len(state.validators) == MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP - 1`
- all validators are not partially or fully withdrawable

Note, this is one of many states which can trigger the behavior of "skipping" withdrawable validators.

In this state, [`get_expected_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-get_expected_withdrawals) returns the empty list and  [`process_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-process_withdrawals) proceeds to the `else` case in the end of the function. The `else` case looks like
```
next_index = state.next_withdrawal_validator_index + MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP
next_validator_index = ValidatorIndex(next_index % len(state.validators))
state.next_withdrawal_validator_index = next_validator_index
```
substituting for our concrete values, it looks like
```
next_index = 0 + len(state.validators) + 1
next_validator_index = ValidatorIndex(1)
state.next_withdrawal_validator_index = ValidatorIndex(1)
```
Now update the state as follows:

- 2 new validators are added to the end of `state.validators`, such that `len(state.validators) == MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP + 1`
- validator at index 0 becomes fully withdrawable.

Note that adding any number of validators >= 2 will trigger the "skipping" behavior.

Now call `process_withdrawals` again. It calls [`get_expected_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-get_expected_withdrawals), which returns the empty list again, since it starts with validator index `state.next_withdrawal_validator_index == ValidatorIndex(1)`, so processes all the `MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP` number of validators at indices > 0.

This means that we have skipped the fully withdrawable validator at index 0. This validator will get processed next time  [`process_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-process_withdrawals) is called, but it seems wrong that it was skipped in the first place.

### Possible solution

I think the "skipping" of withdrawable validators can be avoided by changing the first line of the `else` case in function  [`process_withdrawals`](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-process_withdrawals) to
```
next_index = state.next_withdrawal_validator_index + min(len(state.validators), MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP)
```

**Comment by potuz** [comment]
> Suppose that the input state is satisfying:
> state.next_withdrawal_validator_index == len(state.validators)

This can never happen, we use `% len(state.validators)` in the code. 

So the max value that this can have is `len(state.validators) - 1` in which case the substitution with our concrete values would render `next_validator_index = ValidatorIndex(0)` instead of `1`. 

> This means that we have skipped the fully withdrawable validator at index 0. This validator will get processed next time process_withdrawals is called, but it seems wrong that it was skipped in the first place.

So the validator at index 0 will not be "skipped" with your notation in the next sweep because of the above. 

However: the general phenomenom that we may skip withdrawable validators on sweeps happens, and that's a feature of having a bounded sweep. There's no need to play with the modularity of the number of validators in the state: simply if no validator is withdrawable in one slot, and the sweep is set to start at validator `x + 1`, if validator `x` becomes withdrawable, it will take about 5 days to reach it.

**Comment by andreas-blockswap** [comment]
> This can never happen, we use % len(state.validators) in the code.

Right, changing the assumption to `state.next_withdrawal_validator_index == 0` works with in the example as well. It causes the validator at index 0 to be "skipped", I think.

The reason I say the validator 0 is skipped, is that I would expect that validator to be processed in the second sweep, since we processed all validators in the previous sweep, so should start from index 0 in the second sweep in the example.

**Comment by andreas-blockswap** [comment]
Intuitively: not starting from index 0 in the second sweep breaks the clock, since we wrap around the clock first, but then skip index 0 and start the next iteration of the clock from index 1. Does that make sense?

**Comment by potuz** [comment]
> Intuitively: not starting from index 0 in the second sweep breaks the clock, since we wrap around the clock first, but then skip index 0 and start the next iteration of the clock from index 1. Does that make sense?

Your "fix" doesn't fix this issue (which is non fixable) simply starting before shifts the problem whatever your starting point is, if the next validator that becomes withdrawable is one index before, it will be "skipped" in the next sweep

**Comment by andreas-blockswap** [comment]
Suppose that `state` is a valid state and `payload` a valid payload, satisfying `len(get_expected_withdrawals(state)) < MAX_WITHDRAWALS_PER_PAYLOAD`.
Let `init_state = state.copy()`.
Let `clock_ticks = len(state.validators)`.
Execute `process_withdrawals(state, payload)` and assume it does not throw an exception.

Now the question is which property is the most desirable.

The current property:
```python
state.next_withdrawal_validator_index
  == (init_state.next_withdrawal_validator_index + MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP) % clock_ticks
```
or the other property:
```python
state.next_withdrawal_validator_index
  == (init_state.next_withdrawal_validator_index + processed_validators % clock_ticks
```
where `processed_validators` is the number of validators checked to be withdrawable
```
processed_validators = min(clock_ticks, MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP))
```

**Comment by potuz** [comment]
I honestly think this is irrelevant, this only makes a difference if 
- there are less validators in the init state than `MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP` which will arguably never happen on any network AND
- the very next slot there are more validators in the state than `MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP`, AND
- one validator that was not withdrawable in the first slot became in the second and was right at the boundary

I say it's fine that under such circumstances such unlucky validator can wait 1 slot.
