### ISSUE TITLE
`generate_setup` util is broken due to the incompatible mixing BLS libraries

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3353]
### Issue

The [`generate_setup`](https://github.com/ethereum/consensus-specs/blob/f7352d18cfb91c58b1addb4ea509aedd6e32165c/tests/core/pyspec/eth2spec/utils/kzg.py#L32) helpers use Py-ECC helpers. But the imported `from eth2spec.utils import bls` is `py_arkworks_bls12381` by default.

### How to fix it?

Either change it to full Py-ECC or make the helpers compatible with all different BLS suites.

**Comment by mratsim** [comment]
Affected by this when doing #3357
