### ISSUE TITLE
Electra EIPs for discussion

### ISSUE THREAD

**Issue by djrtwo** [ethereum/consensus-specs#3449]
Please comment with EIPs to be discussed for inclusion in Electra upgrade
For discussion:

| EIP                                                      | Title                                     | CL specs                                                                                      | EL change? | Inclusion status |
|----------------------------------------------------------|-------------------------------------------|-----------------------------------------------------------------------------------------------|------------|----------|
| [EIP-6110](https://eips.ethereum.org/EIPS/eip-6110)    | Supply validator deposits on chain        | [alpha](https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip6110)            | Y          | Included |
| [EIP-6914](https://eips.ethereum.org/EIPS/eip-6914)    | Reuse validator indices                   | [alpha](https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip6914)            | N          | No|
| [EIP-7002](https://eips.ethereum.org/EIPS/eip-7002)    | Execution layer triggerable exits         | [alpha](https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip7002)            | Y          | Included|
| [EIP-7251](https://eips.ethereum.org/EIPS/eip-7251) | Increase the MAX_EFFECTIVE_BALANCE        | [resource collection](https://gist.github.com/michaelneuder/cafabcfcfcccc45e44ab9d6b1c7b4e1d) | N          |Discussion|
| [EIP-7547](https://eips.ethereum.org/EIPS/eip-7547)    | Inclusion lists                           | [draft](https://github.com/hwwhww/consensus-specs/pull/2), [resource collection](https://gist.github.com/michaelneuder/ba32e608c75d48719a7ecba29ec3d64b)                                     | Y          | Discussion |
| [EIP-7549](https://eips.ethereum.org/EIPS/eip-7549)    | Move committee index outside attestation  | [alpha](https://github.com/ethereum/consensus-specs/pull/3559)                                   | N          | Included |
| [EIP-7594](https://github.com/ethereum/EIPs/pull/8105) | PeerDAS - Peer Data Availability Sampling | [draft](https://github.com/ethereum/consensus-specs/pull/3574)                                | N          | Discussion|
| SSZ-ification                                          |                                           |                                                                                               |            |Discussion|
| 1. [EIP-6404](https://eips.ethereum.org/EIPS/eip-6404)   | SSZ Transactions Root                     |                                                                                               | Y          |
| 2. [EIP-6465](https://eips.ethereum.org/EIPS/eip-6465)   | SSZ Withdrawals Root                      |                                                                                               | Y          |
| 3. [EIP-6466](https://eips.ethereum.org/EIPS/eip-6466)   | SSZ Receipts Root                         |                                                                                               | Y          |
| 4. [EIP-6493](https://eips.ethereum.org/EIPS/eip-6493)   | SSZ Transaction Signature Scheme          |                                                                                               | Y          |
| 5. [EIP-7495](https://eips.ethereum.org/EIPS/eip-7495)   | SSZ StableContainer                       |                                                                                               | Y          |

**Comment by dapplion** [comment]
- [EIP-7251: Increase the MAX_EFFECTIVE_BALANCE](https://github.com/ethereum/EIPs/pull/7251)

**Comment by etan-status** [comment]
If this is the Verkle fork, some form of SSZ for the other `_root` beside `state_root`.

- [EIP-6404: SSZ Transactions Root](https://eips.ethereum.org/EIPS/eip-6404)
- [EIP-6465: SSZ Withdrawals Root](https://eips.ethereum.org/EIPS/eip-6465)
- [EIP-6466: SSZ Receipts Root](https://eips.ethereum.org/EIPS/eip-6466)

Still have to revamp the EIPs based on the latest feedback from #typed-transactions, but tracking them here for awareness.

**Comment by abcoathup** [comment]
Upgrade was named Electra on ACDC 113 when Danny was away: https://github.com/ethereum/pm/issues/823#issuecomment-1635053770

**Comment by dapplion** [comment]
[EIP-7549](https://eips.ethereum.org/EIPS/eip-7549): Move committee index outside Attestation

**Comment by abcoathup** [comment]
Add EIP7594: PeerDAS 
https://github.com/ethereum/EIPs/pull/8105/files

**Comment by g11tech** [comment]
Potential EIP proposal
 - https://ethereum-magicians.org/t/track-historicalblockroots-in-beacon-state-accumulators/18201

**Comment by etan-status** [comment]
The complete list of the "SSZ-ification" section:

1. [EIP-7495: SSZ StableContainer](https://eips.ethereum.org/EIPS/eip-7495)
2. [EIP-6493: SSZ Transaction Signature Scheme](https://eips.ethereum.org/EIPS/eip-6493)
3. [EIP-6404: SSZ Transactions Root](https://eips.ethereum.org/EIPS/eip-6404)
4. [EIP-6466: SSZ Receipts Root](https://eips.ethereum.org/EIPS/eip-6466)
5. [EIP-6465: SSZ Withdrawals Root](https://eips.ethereum.org/EIPS/eip-6465)

The one that @g11tech mentioned above is [EIP-7495: SSZ StableContainer](https://eips.ethereum.org/EIPS/eip-7495) -- I think the idea is to _also_ transition `BeaconBlockBody`, `ExecutionPayload` and so on to a format where members retain their location in the merkle tree across forks (e.g., right now, in whisk, [some gindex has to be re-assigned](https://github.com/ethereum/consensus-specs/blob/3727a757450feb6110e2d4e403604572a478343d/pysetup/spec_builders/whisk.py#L30) from [Capella](https://github.com/ethereum/consensus-specs/blob/3727a757450feb6110e2d4e403604572a478343d/pysetup/spec_builders/capella.py#L19), changing tree shape).

Having a stable tree shape means that clients that want to validate presence of specific information can do so without continuously updating their Merkle proof validation logic, as long as the queried information retains its semantic meaning.

**Comment by g11tech** [comment]
another think which I think would greatly benefit solo stakers:
 - https://ethereum-magicians.org/t/el-triggered-validator-pause/18218

**Comment by g11tech** [comment]
> The complete list of the "SSZ-ification" section:
> 
>     1. [EIP-7495: SSZ StableContainer](https://eips.ethereum.org/EIPS/eip-7495)
> 
>     2. [EIP-6493: SSZ Transaction Signature Scheme](https://eips.ethereum.org/EIPS/eip-6493)
> 
>     3. [EIP-6404: SSZ Transactions Root](https://eips.ethereum.org/EIPS/eip-6404)
> 
>     4. [EIP-6466: SSZ Receipts Root](https://eips.ethereum.org/EIPS/eip-6466)
> 
>     5. [EIP-6465: SSZ Withdrawals Root](https://eips.ethereum.org/EIPS/eip-6465)
> 
> 
> The one that @g11tech mentioned above is [EIP-7495: SSZ StableContainer](https://eips.ethereum.org/EIPS/eip-7495) -- I think the idea is to _also_ transition `BeaconBlockBody`, `ExecutionPayload` and so on to a format where members retain their location in the merkle tree across forks (e.g., right now, in whisk, [some gindex has to be re-assigned](https://github.com/ethereum/consensus-specs/blob/3727a757450feb6110e2d4e403604572a478343d/pysetup/spec_builders/whisk.py#L30) from [Capella](https://github.com/ethereum/consensus-specs/blob/3727a757450feb6110e2d4e403604572a478343d/pysetup/spec_builders/capella.py#L19), changing tree shape).
> 
> Having a stable tree shape means that clients that want to validate presence of specific information can do so without continuously updating their Merkle proof validation logic, as long as the queried information retains its semantic meaning.

+1, least we can do in Electra is `StableContainers` for `BeaconBlockBody` and `ExecutionPayload`

**Comment by protolambda** [comment]
EIP-6466, SSZ receipts, is incredibly impactful for its small scope: it makes receipt-proving a lot more viable.

Currently EVM receipts just concatenate log events of completely different contracts, which means applications have no control over their ability to make their log event provable without the user having to prove a potentially multi-megabyte preimage (worst-case does not fit in EVM).
That said, merkleizing to separate log events, each with their contract address source as a mix-in, would also work for some use-cases.

**Comment by etan-status** [comment]
Another interesting addition could be:

- https://gist.github.com/karalabe/e106ac58afc1d611641e543312cf41e3

This does not have to be tied to a fork specifically, but most of the work is necessary as preparation for Verkle anyway, and adding support for minority ELs to use an `eth_getProof` based "database" (without locally storing anything) would grant them veto power, drastically reducing the possibility of a Geth bug to issue a _VALID_ verdict for an incorrect block. Geth is the only EL that can finalize a fake-valid block, so it would have to be the only one providing efficient `eth_getProof` access while processing `engine_newPayload` (before `engine_forkchoiceUpdated`).
