### ISSUE TITLE
Sync EIP-4844 and consensus-specs definitions

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3462]
There is still some naming inconsistencies between [EIP-4844](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md) and [consensus-specs](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/beacon-chain.md):

### Configs/constants
| EIP | CL-specs |
| -------- | --------|
| `BLOB_COMMITMENT_VERSION_KZG` | `VERSIONED_HASH_VERSION_KZG` |

One of them should be renamed.

- For CL, `VERSIONED_HASH_VERSION_KZG` means the version "KZG" of `VersionedHash`.
- For EL, It sounds like `BLOB_COMMITMENT_VERSION` means the version of "blob commitment"?

/cc EIP authors: @dankrad @asn-d6 and co, what do you think about it?

### Custom types
| EIP | CL-specs |
| -------- | --------|
| `Blob: Vector[BLSFieldElement, FIELD_ELEMENTS_PER_BLOB]` | `Blob: ByteVector[BYTES_PER_FIELD_ELEMENT * FIELD_ELEMENTS_PER_BLOB]` |

- They are the same binary data in marshaling.
- CL requires this format in KZG and libraries.
- For EL, I guess EL wanted to simplify it and didn't want to introduce the SSZ `ByteVector` definition?
     - However, `Vector` is also an SSZ definition, so it doesn't wrap up SSZ much.
     - In the EIP [Networking section](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#networking), it says "`blobs` - list of `blob` bytes where each blob is its `BLSFieldElement` list flattened in `big endian`". It seems using `ByteVector` would reduce this note? Also, if we use `ByteVector`, we can remove the `BLSFieldElement` definition from EIP.
 
Therefore, I'm inclined to update the EIP to `ByteVector` format.

**Comment by asn-d6** [comment]
WRT first question, I think at some point in we decided on `VERSIONED_HASH_VERSION_KZG` but we never updated the EIP. I have a small preference for `VERSIONED_HASH_VERSION_KZG`, but it's also OK by me if someone prefers the other naming.

**Comment by hwwhww** [comment]
closing via https://github.com/ethereum/EIPs/pull/7429
