### ISSUE TITLE
Test suite names: BLS and KZG 4844 are confusingly called 'small'

### ISSUE THREAD

**Issue by mratsim** [ethereum/consensus-specs#3478]
Ages ago (in 2019 https://github.com/ethereum/consensus-specs/pull/1320), a huge refactoring introduced suite names.

At the time the BLS test suites were tagged with `suite_name='small'`, unfortunately I do not remember the origin of the name (cc @protolambda  and @asanso) as the full suite did not exist at the time (https://github.com/ethereum/bls12-381-tests).

IIRC it was a minimal set of tests that implementations should pass for interop, was agnostic to minimal/mainnet and included SSZ tests as well but I may very well completely misremember.

https://github.com/ethereum/consensus-specs/blob/8a64a90103ccaa8f5df7aa271af770f811738529/tests/generators/bls/main.py#L514-L525

The KZG-4844 suite reuses the name `small` which AFAIK doesn't mean anything anymore in today's codebase.

https://github.com/ethereum/consensus-specs/blob/8a64a90103ccaa8f5df7aa271af770f811738529/tests/generators/kzg_4844/main.py#L522-L533

This is prone to confusion with the KZG minimal trusted setup as well.

I propose to change:
- bls 'small' to just 'bls' or 'crypto-bls'
- KZG 'small" to 'kzg-mainnet' or 'kzg-minimal' (depending on the trusted setup.

**Comment by hwwhww** [comment]
fixed via #3484
