### ISSUE TITLE
Fork choice attestation validation ignores clock disparity

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/consensus-specs#3480]
While fuzzing Lighthouse I found a case that surprised me a little: it is possible to accept an attestation on gossip from epoch `N - 2` during epoch `N`, which is invalid to apply to fork choice.

The reason for this is that P2P attestation validation allows for 500ms of clock disparity, while fork choice does not:

```python
def validate_target_epoch_against_current_time(store: Store, attestation: Attestation) -> None:
    target = attestation.data.target

    # Attestations must be from the current or previous epoch
    current_epoch = compute_epoch_at_slot(get_current_slot(store))
    # Use GENESIS_EPOCH for previous when genesis to avoid underflow
    previous_epoch = current_epoch - 1 if current_epoch > GENESIS_EPOCH else GENESIS_EPOCH
    # If attestation target is from a future epoch, delay consideration until the epoch arrives
    assert target.epoch in [current_epoch, previous_epoch]
```

[(link)](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/fork-choice.md#validate_target_epoch_against_current_time)

This isn't necessarily a problem with the spec unless we expect this invariant to hold:

```python3
accepted_on_gossip(attestation) -> validate_on_attestation(store, att, False) == None
```

As far as I can tell this doesn't change with Deneb either, as `validate_target_epoch_against_current_time` continues to ignore the clock disparity allowance applied on the P2P layer: https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/p2p-interface.md#beacon_aggregate_and_proof.

Lighthouse issue: https://github.com/sigp/lighthouse/issues/4633

**Comment by michaelsproul** [comment]
If the stated invariant isn't desired, then it's a simple matter to clean up Lighthouse's error handling so that this doesn't result in a nasty `ERROR` log. There is no other ill effect.

**Comment by mkalinin** [comment]
IMO, network restrictions are to protect a network from DoSing it with stale data while FC has its own constraints. I don't think that these two should match, i.e. don't see that invariant holding to be really helpful. Clock disparity workaround gives 500ms window where stale consensus data can sweep in, this trade off looks acceptable to me.

**Comment by michaelsproul** [comment]
@mkalinin Yeah having thought about it more I agree this is a non-issue on the spec side.

Even if we did try to make fork choice accept any attestation received on gossip it would still break due to timing, e.g. we could accept an attestation on gossip 0.5ms before it becomes stale -> some processing/queuing could take 0.5ms -> fork choice would see the attestation as stale and rejects it.

We'll fix this on the Lighthouse side
