### ISSUE TITLE
Feature Request: Having the justified block in the light client update data

### ISSUE THREAD

**Issue by aeryz** [ethereum/consensus-specs#3502]
Currently, when the finality update or light client update is requested, attested and finalized headers are returned. But the 2 epoch difference between the finalized and the attested header is not good for the UX. Because there are 12.8 minutes between those two.

How about adding `justified_header` which is 1 epoch behind the `attested_header` so that the light clients can have the option to trust it or not based on their use case?

**Comment by hwwhww** [comment]
no objection from me. /cc @etan-status @dapplion

**Comment by dapplion** [comment]
I understand the use-case, but when Confirmation Rule https://github.com/ethereum/consensus-specs/pull/3339 lands the range of headers we could potentially include widens.

Adding more headers includes the bandwidth requirements for all consumers. I would like to see a more in-depth look into the matter before including the justified header

**Comment by aeryz** [comment]
Closing the issue since the effort to add this would not worth it considering the Confirmation Rule #3339. Thanks!
