### ISSUE TITLE
There are two parameters about the number of validators in a committee

### ISSUE THREAD

**Issue by Mart1i1n** [ethereum/consensus-specs#3511]
The first parameter is TARGET\_COMMITTEE\_SIZE, it is outdated.
We should use the second parameter which is MAX_VALIDATORS_PER_COMMITTEE.

**Comment by hwwhww** [comment]
`TARGET_COMMITTEE_SIZE` is kind of the lower-bound of the safe minimum committee size. 

Here is the in-depth introduction: https://eth2book.info/capella/annotated-spec/#target_committee_size
