### ISSUE TITLE
Add more single_merkle_proof tests

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3539]
Suggested by @potuz, having randomized `BeaconBlockBody` would be helpful to detect the edge cases.

**Comment by ppopth** [comment]
Like fuzz testing?

**Comment by potuz** [comment]
The static spectests have some testvectors that are randomly generated. In this particular case, our implementation had a bug that could have been caught early if the testvector had some slashings, the test vector had a full block, but the block didn't have any slashings in it.

**Comment by hwwhww** [comment]
@ppopth 

I'm thinking about just creating ~10 test cases with different RNG seeds and utilizing the existing [`random_block_deneb`](https://github.com/ethereum/consensus-specs/blob/36f0bb0ed62b463947fda97f42f8ddebc9565587/tests/core/pyspec/eth2spec/test/utils/randomized_block_tests.py#L239) helper.

**Comment by hwwhww** [comment]
closing via #3555
