### ISSUE TITLE
Init Electra

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3603]
Two steps

1. Merge [EIP-6110](https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip6110) and [EIP-7002](https://github.com/ethereum/consensus-specs/tree/dev/specs/_features/eip7002) into Electra
2. Merge EIP-7549 when it's ready

Note: the full scope of Electra is still TBD

**Comment by ralexstokes** [comment]
I think we can go ahead and close this, unless you want to repurpose for electra tracking generally
