### ISSUE TITLE
Cannot do Dev intsallation succefully (make spec excutable)

### ISSUE THREAD

**Issue by TonyP4N** [ethereum/consensus-specs#3604]
### **By following the given instruction, I encountered some errors during the process:** 
I aim to use the `Capella fork` mainnet Python code.

![图片](https://github.com/ethereum/consensus-specs/assets/92439213/ad69c5d7-0247-4cad-8532-3e5a1fea7938)

### **Using Python version `3.8.10`**
_TypeError: 'type' object is not subscriptable_
![图片](https://github.com/ethereum/consensus-specs/assets/92439213/c5e62c01-d037-45d1-9ea5-41a693e2f7d7)

### **Using Python version `3.10.13`**
_ModuleNotFoundError: No module named 'distutils.core'_
![图片](https://github.com/ethereum/consensus-specs/assets/92439213/a251df60-3139-48f2-9cb0-f0b82c2a5cb7)

**Comment by hwwhww** [comment]
@TonyP4N did you install `pip`?

If you use the Makefile commands to use venv, you can try:
```
make install_test
make pyspec
```

**Comment by TonyP4N** [comment]
Hi, @hwwhww 
Thank you for your advice! :-)

Ya, I did use `make install_test`, and the output was like:
![图片](https://github.com/ethereum/consensus-specs/assets/92439213/bcb87626-2b55-40ba-8ba3-925ad74fd23f)

The pip version is 20.0.2. Is that all right?

**Comment by TonyP4N** [comment]
Is there any advice please?
With best regards.

**Comment by TonyP4N** [comment]
Hi @hwwhww,
I solved the issue using **python3.11.2** and **pip 24.0**. :+1: 

Thanks, the issue can be closed .
