### ISSUE TITLE
Clarify `voluntary_exits` gossip topic after Capella

### ISSUE THREAD

**Issue by zilm13** [ethereum/consensus-specs#3638]
I read the spec as topic is fixed to Capella after Capella:
https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/p2p-interface.md?plain=1#L121
While EIP-7044 is not clear on this.
Do we use current fork topic for gossip or Capella in Deneb and after?

**Comment by dapplion** [comment]
I understand it's current fork for symmetry with all other topics

**Comment by zilm13** [comment]
@dapplion we do the same but "due to the lock-in use of `CAPELLA_FORK_VERSION`" confuses me

**Comment by g11tech** [comment]
yes as per lodestar impl, only the signature fork domain stays fixed while current topic is used
