### ISSUE TITLE
EIP-7251: effective balance check for pending withdrawals is too strict

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/consensus-specs#3655]
Refer:

https://github.com/ethereum/consensus-specs/blob/b18bbd8c6199e6f310fac81ee790120c8136ced6/specs/_features/eip7251/beacon-chain.md?plain=1#L689

I think this should be `>=` rather than `==`, as it implies only validators with exactly `MIN_ACTIVATION_BALANCE` can have partial withdrawals (which is not the intent).

**Comment by ajsutton** [comment]
Isn't the effective balance capped to `MIN_ACTIVATION_BALANCE` anyway?  (unless some of the MaxEB stuff has already been merged).

**Comment by mkalinin** [comment]
> Isn't the effective balance capped to `MIN_ACTIVATION_BALANCE` anyway? (unless some of the MaxEB stuff has already been merged).

In the partial withdrawals logic the check should be `>=` as partial withdrawals are applied to 0x02 withdrawal credentials for which EB can be greater than `MIN_ACTIVATION_BALANCE`
