### ISSUE TITLE
Electra open questions

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/consensus-specs#3664]
## EIP-7251

https://github.com/ethereum/consensus-specs/issues/3673

#### How to handle Deneb `Attestation`s that can be included in Electra but won't be compatible with the new format?

~There will be an epoch's worth of attestations scheduled in the last Deneb epoch that are valid to include in the first epoch of Electra but are incompatible with the new attestation format.~

~What should we do, if anything about this transition period?~
  * ~one suggestion: clients broadcast both formats in the last deneb epoch, with care taken to not produce slashable messages~
  * ~another suggestion: extend block with extra field for the pre-electra attestations and just allow the deneb style during the first epoch of electra (otherwise validate this new list is empty in electra)~

Update: after discussions with client teams, we decided to do nothing here.

### TODO
- [ ] revisit these tests once we decide how to handle https://github.com/ethereum/consensus-specs/pull/3668/commits/353bbb02a6d19352d28019558bac8fb8d2763129
- [ ] revisit the 'randomization' tests, to ensure we have good coverage across all operations types and scenarios

**Comment by dapplion** [comment]
Another option:

```diff
- assert data.index == 0
+ assert data.index == 0 || compute_epoch_at_slot(data.slot) < ELECTRA_FORK_EPOCH
```

Which allows block proposers to re-package deneb attestations into electra ones for the first epoch. This condition can be changed to wait for electra finaility

**Comment by ralexstokes** [comment]
moving remainder here to #3799
