### ISSUE TITLE
EIP-7594 - Shorten the new introduced ENR record key (`custody_subnet_count`).

### ISSUE THREAD

**Issue by nalepae** [ethereum/consensus-specs#3744]
**Description of the issue:**

[EIP-7594](https://github.com/ethereum/consensus-specs/blob/dev/specs/_features/eip7594/p2p-interface.md#the-discovery-domain-discv5) introduces a new ENR record: `custody_subnet_count`.

As highlighted by @wemeetagain in https://github.com/ethereum/consensus-specs/pull/3644, the maximum encoded size of a node record is 300 bytes. ([Source](https://github.com/ethereum/devp2p/blob/master/enr.md#rlp-encoding)).

For information here is what an ENR entries looks like with this new record:
![image](https://github.com/ethereum/consensus-specs/assets/4943830/2a0d8af3-4e14-41d6-a8c6-66e2d4f97456)

The `custody_subnet_count` key by itself consumes 20 bytes, so almost 7% of the total available space in the ENR.

**Proposal:**
Remplace this key by a shorter one.

**Comment by ppopth** [comment]
That makes sense. I would say `csc` (custody subnet count).

**Comment by jimmygchen** [comment]
`csc` could be a bit cryptic for those not familiar with the context. I'm leaning towards `custnets` or `custnetcnt` as it aligns well with our existing keys `attnets` and `syncnets`; and it's also slightly easier to read. What do you think?

**Comment by dapplion** [comment]
Why not just `custody`? Do we anticipate any future property that may conflict in that namespace?

**Comment by nalepae** [comment]
Related:
The specification states: `custody_subnet_count` is a `SSZ uint64` ([Source](https://github.com/ethereum/consensus-specs/blob/dev/specs/_features/eip7594/p2p-interface.md#custody_subnet_count)).

Unless we wish to have more than 255 subnets, we waste 3 bytes compared to `uint8`.
We could use `uint8` or `uint16` to be more conservative.

**Comment by ppopth** [comment]
> `csc` could be a bit cryptic for those not familiar with the context

I think it's cryptic for now, but people can get familiar with it over time.

**Comment by hwwhww** [comment]
closing via #3772
