### ISSUE TITLE
Consider migrating `MIN_ACTIVATION_BALANCE` and `MAX_EFFECTIVE_BALANCE_ELECTRA` to config instead of preset

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/consensus-specs#3753]
`MIN_ACTIVATION_BALANCE` and `MAX_EFFECTIVE_BALANCE_ELECTRA` are currently preset values, but don't directly correspond to "static" or "compile-time" constants like the other presets.

I would suggest moving them to configuration instead (e.g. see [`EJECTION_BALANCE` here](https://github.com/ethereum/consensus-specs/blob/1c081a04d0d741378bbbd44e0c9f503e06e61ba1/configs/mainnet.yaml#L84))

**Comment by hwwhww** [comment]
I think my judgment is if the given setting would be configurable in devnets or tests.

iiuc, `EJECTION_BALANCE` setting was debatable so we set it to config. I'm not sure if we should actually move it to preset now or not. 🤔

**Comment by ralexstokes** [comment]
yeah, fair enough, ill close this issue :)
