### ISSUE TITLE
How the program pass the spec and state to test_one_basic_attestation function

### ISSUE THREAD

**Issue by jwbda** [ethereum/consensus-specs#3842]
Hi, would you mind help me with this question:

How the program pass the `spec` and `state` to `test_one_basic_attestation` function

https://github.com/ethereum/consensus-specs/blob/dc5f74da0e9834fa842cdcb33c64b3a1fb1ad579/tests/core/pyspec/eth2spec/test/phase0/block_processing/test_process_attestation.py#L27

The code is kind of complicated to me, pls help, thanks in advance.

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @jwbda
