### ISSUE TITLE
Add unit test for `get_execution_requests`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#4016]
Issue: `get_execution_requests ` in https://github.com/ethereum/consensus-specs/blob/dev/specs/electra/validator.md#execution-requests is untested.

How to fix it:
Add a new file `tests/core/pyspec/eth2spec/test/electra/unittests/validator/test_validator.py` with some test cases to cover it.

Hint:
1. Remember to add an empty `tests/core/pyspec/eth2spec/test/electra/unittests/validator/__init__.py` file for the new folder.
2. Use `eth2spec.utils.ssz.ssz_impl.ssz_serialize` helper to generate the input `execution_requests: Sequence[bytes]`.

**Comment by 0xshikhar** [comment]
Hey @hwwhww  , would like to work on this task - can you assign me that. Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

**Comment by 0xshikhar** [comment]
Hey @hwwhww, sure its alright. Will work on next one:)

**Comment by hwwhww** [comment]
actually, closing via #3998
