### ISSUE TITLE
[spec test]: Ensure duplicate deposits are handled successfully during `electra` epoch processing

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/consensus-specs#4021]
We may already have a test case for this, but we should verify and write one if we don't.

This issue is coming from a bug on `mekong` where three clients incorrectly handled the following scenario:

Two deposits to the same validator in an epoch (the `mekong` setting had a deposit in one block and then another two blocks later to the same validator). The first deposit was fresh (aka the validator was not on-chain beforehand), and the second would be considered a "top-up".

During epoch processing, we had two separate issues:

1) The two deposits were treated as one (e.g. for two deposits of 32 ETH, the resulting state only had one validator of 32 ETH, instead of 64 ETH).
2) The same validator was added to the state's registry twice, one for each deposit (rather than one validator with the balance summing the amount in each deposit).

**Comment by 0xshikhar** [comment]
Hey @ralexstokes , would like to work on this task - can you assign me that. Could you clarify the remaining tasks for this issue? Any additional context would be appreciated. Thanks!

**Comment by ralexstokes** [comment]
hi @0xshikhar I think @mkalinin is looking at this, but if you want to make a pass at electra spec tests broadly, that would be very helpful

**Comment by mkalinin** [comment]
I think we need more tests to cover epoch processing in a way that would help revealing such bugs before testnets, more detailed description is here https://github.com/ethereum/consensus-specs/issues/4025. @0xshikhar this is something worth looking into as well
